feat: add PCF metrics counters
omec-project/pcf pull request #151
Opened 2024-10-02 09:26 UTC by dariofaccin

This PR adds two new 5G specific metrics, `pcf_smpolicy` and `pcf_policy_authorization` to exported metrics via Prometheus.
The scope of the metrics is the following:
* `pcf_smpolicy`: this metric counts the total number of Session Management policy queries to PCF; the metric stores the query type (`create`, `get`, `update`, `delete`), the DNN and the result (`SUCCESS`, `FAILURE`);
* `pcf_policy_authorization`: this metric counts the total number policy authorization queries to PCF; the metric stores the query type (`create`, `get`, `update`, `delete`), the resource type (`application_sessions`, `events_subscriptions`) and the result (`SUCCESS`, `FAILURE`).

2024-10-02 11:30 UTC, gatici approved these changes

2024-10-05 12:17 UTC, thakurajayL requested changes

2024-10-05 12:17 UTC, thakurajayL commented on producer/smpolicy.go
> +	if problems != nil {
Should it be response != nil ? 
if problem is not nil then response is nil and it would lead to crash.

2024-10-05 12:17 UTC, thakurajayL commented on producer/smpolicy.go
> +		stats.IncrementPcfSmPolicyStats("get", "UNKNOWN_DNN", "SUCCESS")
Should not this be FAILURE?

2024-10-05 12:17 UTC, thakurajayL commented on producer/smpolicy.go
> +	if getProblemDetails != nil {
1. getResponse would be nil if getProblemDetails is not nil.
2. Can we have consistency in naming these variables?

2024-10-08 10:07 UTC, thakurajayL approved these changes

2024-10-08 10:07 UTC, merged